CREATE DATABASE customer_behavior_db;
USE customer_behavior_db;
SELECT * FROM customer;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender, Sum(purchase_amount) as revenue
from customer
group by gender
